# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

data_bytes <- function(h5file, groupname, dataname) {
    .Call('RColumbo_data_bytes', PACKAGE = 'RColumbo', h5file, groupname, dataname)
}

get_rownum_h5 <- function(h5file, groupname, dataname) {
    .Call('RColumbo_get_rownum_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname)
}

get_colnum_h5 <- function(h5file, groupname, dataname) {
    .Call('RColumbo_get_colnum_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname)
}

getGroups <- function(h5file) {
    .Call('RColumbo_getGroups', PACKAGE = 'RColumbo', h5file)
}

getObjects <- function(h5file, groupname) {
    .Call('RColumbo_getObjects', PACKAGE = 'RColumbo', h5file, groupname)
}

get_arraydim <- function(h5file, groupname, dataname) {
    .Call('RColumbo_get_arraydim', PACKAGE = 'RColumbo', h5file, groupname, dataname)
}

read_fmat_h5 <- function(hap_h5file, groupname, dataname, offset, chunksize) {
    .Call('RColumbo_read_fmat_h5', PACKAGE = 'RColumbo', hap_h5file, groupname, dataname, offset, chunksize)
}

read_dmat_h5 <- function(hap_h5file, groupname, dataname, offset, chunksize) {
    .Call('RColumbo_read_dmat_h5', PACKAGE = 'RColumbo', hap_h5file, groupname, dataname, offset, chunksize)
}

read_dmat_chunk_ind <- function(h5file, groupname, dataname, indvec) {
    .Call('RColumbo_read_dmat_chunk_ind', PACKAGE = 'RColumbo', h5file, groupname, dataname, indvec)
}

read_fmat_chunk_ind <- function(h5file, groupname, dataname, indvec) {
    .Call('RColumbo_read_fmat_chunk_ind', PACKAGE = 'RColumbo', h5file, groupname, dataname, indvec)
}

read_h5_df_col <- function(h5file, groupname, dataname, dclass, col_index) {
    .Call('RColumbo_read_h5_df_col', PACKAGE = 'RColumbo', h5file, groupname, dataname, dclass, col_index)
}

read_Rint_h5 <- function(h5file, groupname, dataname) {
    .Call('RColumbo_read_Rint_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname)
}

read_float_h5 <- function(h5file, groupname, dataname, offset, chunksize) {
    .Call('RColumbo_read_float_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, offset, chunksize)
}

read_double_h5 <- function(h5file, groupname, dataname, offset, chunksize) {
    .Call('RColumbo_read_double_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, offset, chunksize)
}

read_Rfloat_h5 <- function(h5file, groupname, dataname) {
    .Call('RColumbo_read_Rfloat_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname)
}

intersect_col <- function(h5file1, h5groupname1, h5colname1, h5file2, h5groupname2, h5colname2) {
    .Call('RColumbo_intersect_col', PACKAGE = 'RColumbo', h5file1, h5groupname1, h5colname1, h5file2, h5groupname2, h5colname2)
}

read_2dfmat_h5 <- function(h5file, groupname, dataname, row_offset, col_offset, row_chunksize, col_chunksize) {
    .Call('RColumbo_read_2dfmat_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, row_offset, col_offset, row_chunksize, col_chunksize)
}

read_2ddmat_h5 <- function(h5file, groupname, dataname, row_offset, col_offset, row_chunksize, col_chunksize) {
    .Call('RColumbo_read_2ddmat_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, row_offset, col_offset, row_chunksize, col_chunksize)
}

dmeansd_h5 <- function(h5file, groupname, dataname, dim = 0L) {
    .Call('RColumbo_dmeansd_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, dim)
}

write_dmatrix_h5 <- function(h5file, groupname, dataname, Nsnps, Nind, data, deflate_level) {
    .Call('RColumbo_write_dmatrix_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, Nsnps, Nind, data, deflate_level)
}

write_Rint_h5 <- function(h5file, groupname, dataname, data, deflate_level) {
    .Call('RColumbo_write_Rint_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, data, deflate_level)
}

write_Rnumeric_h5 <- function(h5file, groupname, dataname, data, deflate_level) {
    .Call('RColumbo_write_Rnumeric_h5', PACKAGE = 'RColumbo', h5file, groupname, dataname, data, deflate_level)
}

convertTSparse <- function(mat) {
    .Call('RColumbo_convertTSparse', PACKAGE = 'RColumbo', mat)
}

findbandwidth <- function(i, j, x, cutoff) {
    .Call('RColumbo_findbandwidth', PACKAGE = 'RColumbo', i, j, x, cutoff)
}

make_long <- function(vchrom, vpos, posmap) {
    .Call('RColumbo_make_long', PACKAGE = 'RColumbo', vchrom, vpos, posmap)
}

findcutoff <- function(i, j, x, bandwidth) {
    .Call('RColumbo_findcutoff', PACKAGE = 'RColumbo', i, j, x, bandwidth)
}

read_fmat_gz <- function(gzfile, chunksize, nrows, keeprow, ncols) {
    .Call('RColumbo_read_fmat_gz', PACKAGE = 'RColumbo', gzfile, chunksize, nrows, keeprow, ncols)
}

write_haplotype_h5 <- function(hap_gzfile, hap_h5file, nrows, ncols, chunksize, deflate_level) {
    .Call('RColumbo_write_haplotype_h5', PACKAGE = 'RColumbo', hap_gzfile, hap_h5file, nrows, ncols, chunksize, deflate_level)
}

read_flip <- function(hap_h5file, indexes) {
    .Call('RColumbo_read_flip', PACKAGE = 'RColumbo', hap_h5file, indexes)
}

read_haplotype_ind_h5 <- function(hap_h5file, indexes) {
    .Call('RColumbo_read_haplotype_ind_h5', PACKAGE = 'RColumbo', hap_h5file, indexes)
}

read_dmat_ind_h5 <- function(hap_h5file, groupname, dataname, indexes) {
    .Call('RColumbo_read_dmat_ind_h5', PACKAGE = 'RColumbo', hap_h5file, groupname, dataname, indexes)
}

read_dmat_rowname <- function(h5file, annogroupname, annocolname, datagroupname, datacolname, queryvec) {
    .Call('RColumbo_read_dmat_rowname', PACKAGE = 'RColumbo', h5file, annogroupname, annocolname, datagroupname, datacolname, queryvec)
}

read_fmat_rowname <- function(h5file, annogroupname, annocolname, datagroupname, datacolname, queryvec) {
    .Call('RColumbo_read_fmat_rowname', PACKAGE = 'RColumbo', h5file, annogroupname, annocolname, datagroupname, datacolname, queryvec)
}

ip_cov <- function(Hpanela, Hpanelb, isDiag) {
    .Call('RColumbo_ip_cov', PACKAGE = 'RColumbo', Hpanela, Hpanelb, isDiag)
}

flip_hap <- function(hap_h5file, index, chunk, chunksize, nSNPs) {
    .Call('RColumbo_flip_hap', PACKAGE = 'RColumbo', hap_h5file, index, chunk, chunksize, nSNPs)
}

read_haplotype_h5 <- function(hap_h5file, readSNPs, skipSNPs) {
    .Call('RColumbo_read_haplotype_h5', PACKAGE = 'RColumbo', hap_h5file, readSNPs, skipSNPs)
}

