# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_haplotype_h5 <- function(hap_gzfile, hap_h5file, nrows, ncols, chunksize) {
    .Call('RColumbo_write_haplotype_h5', PACKAGE = 'RColumbo', hap_gzfile, hap_h5file, nrows, ncols, chunksize)
}

read_flip <- function(hap_h5file, indexes) {
    .Call('RColumbo_read_flip', PACKAGE = 'RColumbo', hap_h5file, indexes)
}

read_haplotype_ind_h5 <- function(hap_h5file, indexes) {
    .Call('RColumbo_read_haplotype_ind_h5', PACKAGE = 'RColumbo', hap_h5file, indexes)
}

ip_cov <- function(Hpanela, Hpanelb, isDiag) {
    .Call('RColumbo_ip_cov', PACKAGE = 'RColumbo', Hpanela, Hpanelb, isDiag)
}

flip_hap <- function(hap_h5file, index, chunk, chunksize, nSNPs) {
    .Call('RColumbo_flip_hap', PACKAGE = 'RColumbo', hap_h5file, index, chunk, chunksize, nSNPs)
}

cov_2_cor <- function(covmat, rowvara, colvarb, isDiag) {
    invisible(.Call('RColumbo_cov_2_cor', PACKAGE = 'RColumbo', covmat, rowvara, colvarb, isDiag))
}

compute_shrinkage <- function(distmat, S, hmata, hmatb, theta, m, Ne, cutoff, isDiag) {
    invisible(.Call('RColumbo_compute_shrinkage', PACKAGE = 'RColumbo', distmat, S, hmata, hmatb, theta, m, Ne, cutoff, isDiag))
}

calcLD <- function(hmata, hmatb, mapa, mapb, distmat, m, Ne, cutoff, aind, bind) {
    invisible(.Call('RColumbo_calcLD', PACKAGE = 'RColumbo', hmata, hmatb, mapa, mapb, distmat, m, Ne, cutoff, aind, bind))
}

gen_sparsemat <- function(ldmat, istart, jstart, nSNPs) {
    .Call('RColumbo_gen_sparsemat', PACKAGE = 'RColumbo', ldmat, istart, jstart, nSNPs)
}

flip_hap_LD <- function(hap_h5file, index, map, m, Ne, cutoff, i, j, chunksize) {
    .Call('RColumbo_flip_hap_LD', PACKAGE = 'RColumbo', hap_h5file, index, map, m, Ne, cutoff, i, j, chunksize)
}

read_haplotype_h5 <- function(hap_h5file, readSNPs, skipSNPs = 0L) {
    .Call('RColumbo_read_haplotype_h5', PACKAGE = 'RColumbo', hap_h5file, readSNPs, skipSNPs)
}

gen_rows <- function(i, nrows, chunksize) {
    .Call('RColumbo_gen_rows', PACKAGE = 'RColumbo', i, nrows, chunksize)
}

read_hap_txt <- function(inhapfile) {
    .Call('RColumbo_read_hap_txt', PACKAGE = 'RColumbo', inhapfile)
}

read_hap_h5 <- function(inhapfile) {
    .Call('RColumbo_read_hap_h5', PACKAGE = 'RColumbo', inhapfile)
}

p_sparse_LD <- function(cummap, Hpanel, Ne, m, cutoff, chunksize, i, j) {
    .Call('RColumbo_p_sparse_LD', PACKAGE = 'RColumbo', cummap, Hpanel, Ne, m, cutoff, chunksize, i, j)
}

sparse_LD <- function(cummap, Hpanel, Ne, m, cutoff, report_every) {
    .Call('RColumbo_sparse_LD', PACKAGE = 'RColumbo', cummap, Hpanel, Ne, m, cutoff, report_every)
}

