# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('RColumbo_rcpparma_hello_world', PACKAGE = 'RColumbo')
}

pcov <- function(tH, c1, c2, isDiag) {
    .Call('RColumbo_pcov', PACKAGE = 'RColumbo', tH, c1, c2, isDiag)
}

gen_rows <- function(i, nrows, chunksize) {
    .Call('RColumbo_gen_rows', PACKAGE = 'RColumbo', i, nrows, chunksize)
}

sparse_LD <- function(cummap, Hpanel, Ne, m, cutoff) {
    .Call('RColumbo_sparse_LD', PACKAGE = 'RColumbo', cummap, Hpanel, Ne, m, cutoff)
}

